### ISSUE TITLE
Use auditd log for alerting on apparmor systems

### ISSUE THREAD

**Issue by achrefbensaad** [kubearmor/KubeArmor#1009]
### Short Description

Currently, kubearmor uses eBPF for identifying policy violations i.e., it applies checks at kretprobes for the syscalls of interest and checks the return value. If the return value is "Permission Denied" then the policy matching is done to figure out which policy caused this event.

The advantage with this approach is that it works regardless of the LSM in use.

The problem with this approach is that if the syscall returns Permission Denied due to some different reason which is not-kubearmor related then the policy-matcher would still tag it in the context of kubearmor since kubearmor's policy-matcher has no way of knowing whether the denial is because of its own policy.

### Proposal:

Decouple alerting from ebpf programs by using auditd logs. In case of apparmor, the kernel audit logs are available. These audit logs contain the apparmor profile information that caused the denial event. The profile information can be used to map the namespace, container, pod details.

### Tasks
- [x] use kernel audit using netlink to fetch audit logs
- [x] Handling audit/block events natively in apparmor
- [x] fallback logic if the audit mechanism is not available or based on explicit configuration option
- [x] handling process/file/network and creating telemetry alert based on the audit log
- [x] Add system tests
- [x] when bpf-lsm is used as the enforcer then default back to ebpf. Create a separate issue to handle alert events using bpf-lsm.
