### ISSUE TITLE
Scale testing for Kubearmor Relay

### ISSUE THREAD

**Issue by Shreyas220** [kubearmor/KubeArmor#1154]
## Request

**Short Description**
We need to perform scale testing for Kubearmor Relay to ensure that it can handle a high volume of traffic without degrading performance or crashing. The goal of this testing is to determine the maximum capacity of the system and identify any bottlenecks that need to be addressed.

**Isuues Found**

- We are dropping events in PushLog() and PushMsg() in kubearmor if all the channels are busy 
- We are dropping events in Relay server if all the channels for client 
- Relay server not consuming events from grpc stream fast enough  
- Buffer size is a bottleneck in relay server causing event drops. 
- Memory utilization of relay for 100 node cluster is alot  

**Tasks**
- [x] Metric when overload relay server
- [x] Increasing the buffer size to reduce dropping of logs 
-  [x] Debug  why the events sent from kubearmor are not equal to events received in relay-server
- [x] Develop a buffer channel to receive events from grpc stream and separate logic to add events to log/alert/msgstruct.
- [x] Determine the number of nodes that the relay server can handle requests from.
- [ ] Make the buffer to receive events dynamic by fetching the number of Kubearmor and multiplying it with the max burst size .
- [ ] Identify a way to manually release the buffer memory for a 100-node cluster with high memory utilization

![Untitled-2023-03-17-0128](https://user-images.githubusercontent.com/55346934/226273460-882f4f40-e5c2-4a9a-a6ec-2791a67babf1.png)

**Comment by Shreyas220** [comment]
There are two points in our current scaling relay system that could potentially create problems:

 - Non-blocking code for pushing logs into the LogStructs channel can result in dropped logs.
  This occurs when the code sends logs to the client without first checking if the channel is blocked. As a result, some logs may be dropped, and the client will not receive them.


![image](https://user-images.githubusercontent.com/55346934/226277050-dc3f087a-b13c-4571-b1e9-0ec41ef9bff0.png)


-  Sending alerts/logs to the first connection that is free may deprive other clients of the same alerts/logs. 
This occurs when the code sends alerts/logs to the first free connection that it finds. As a result, other clients may not receive the same alerts/logs, even if they are relevant to them.
![image](https://user-images.githubusercontent.com/55346934/226275831-78db6b64-ecf4-42b2-9168-acaa43912c82.png)

**Comment by Shreyas220** [comment]
### Current Design
Currently, for every Kubearmor instance, we create 10 concurrent connections, and each connection runs 3 goroutines for WatchLogs, WatchAlert, and WatchMsg. This means that for a 100-node cluster, we have 3000 goroutines running.

### Proposed Design
To optimize the connections and goroutines, we can decrease the number of goroutines running and connect to the Kubearmor relay server first. When we send a request to the server, we can get the clientUuid, and with every new connection, we can send the clientUuid to one connection from each clientuid. This would reduce the number of redundant connections and improve performance

**Comment by Shreyas220** [comment]
proposed design 
https://gist.github.com/Shreyas220/60baea6c3f140fa6ffc1f55f647855e6
