### ISSUE TITLE
RedHat OpenShift Certified Operator

### ISSUE THREAD

**Issue by rksharma95** [kubearmor/KubeArmor#1200]
## Feature Request

**Short Description**

Get KubeArmor Operator certified with RedHat OpenShift Product Certification,it'll provide the users with confidence that the KubeArmor Operator has been tested and verified to work on OpenShift in production env. This issue tracks the steps needed to complete the certification process.

**Requirements**

To certify the operator, these [requirements](https://access.redhat.com/documentation/en-us/red_hat_software_certification/8.59/html/red_hat_openshift_software_certification_policy_guide/assembly-products-managed-by-an-operator_openshift-sw-cert-policy-container-images) must be met.

**Describe the solution you'd like**

```[tasklist]
### Tasks
- [ ] https://github.com/kubearmor/KubeArmor/issues/1201
- [ ] https://github.com/kubearmor/KubeArmor/issues/1409
- [x] Certify Each Container Image Managed by the KubeArmor Operator.
- [x] Address the requirements to be met by the Operator
- [x] Test the operator against the targeted OpenShift version.
- [x] Submit the operator for certification to the Red Hat Ecosystem Catalog.
```

**Comment by Horiodino** [comment]
hey guys i found this project quite entrusting , i don't have that much idea here but i would like to contribute 
can you guys guide a little bit please ...

**Comment by rksharma95** [comment]
@Horiodino Thank you for reaching out and showing interest in contributing, I wanted to let you know that this issue  is already assigned and is currently in-progress. It would be great if you can give any feedback here #1246 .

However, there are several other [open issues](https://github.com/kubearmor/KubeArmor/issues) available that you can contribute to and make a meaningful impact. Feel free to browse through them.

**Comment by DelusionalOptimist** [comment]
Keeping this open as I think some tasks around certification are still pending. Close if otherwise.
cc @rksharma95

**Comment by rksharma95** [comment]
> Keeping this open as I think some tasks around certification are still pending. Close if otherwise. cc @rksharma95

yes there are some pending tasks.

**Comment by rksharma95** [comment]
PR: https://github.com/redhat-openshift-ecosystem/certified-operators/pull/2916
