### ISSUE TITLE
RedHat UBI as the Base Image for All Containerized Applications

### ISSUE THREAD

**Issue by rksharma95** [kubearmor/KubeArmor#1201]
## Feature Request

I propose that we adopt [RedHat Universal Base Image](https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image) (UBI) as our standard base image for all containerized applications  (KubeArmor, KubeArmor-Init, KubeArmor Controller, and KubeArmor Relay) going forward. We've already built and get certified the Redhat UBI based Container Images for KubeArmor and KubeArmor-Init. 

UBI, a minimal, but comprehensive, operating system image designed to be used as a base image for building container images that are portable and **certified to work with Red Hat software**. Adopting UBI as base image brings advantages:

- `Security`: UBI inherits most features of RHEL and follows updates lifecycle for the packages same as RHEL.
- `Support`: Red Hat provides support for UBI and a large community to get help with any issues. 
- `Licensing`: UBI ensure compliance with Red Hat's open source licensing requirements.

for more information please refer 
[what is redhat ubi](https://developers.redhat.com/blog/2019/10/09/what-is-red-hat-universal-base-image) and
[red-hat-developer-ubi_ebook.pdf](https://github.com/kubearmor/KubeArmor/files/11259942/red-hat-developer-ubi_ebook.pdf)

```[tasklist]
### Tasks
- [x] Identify requirements (packages and capabilities) for each application.
- [x] Build and Test UBI based Container Images (except kubearmor) on Docker, CRI-O and Containerd
- [x] Build Container Image to be run as non-root user. (It's one of the requirements to get certified by redhat)
- [x] Update CI workflow to Build and Push UBI based images
- [x] Get Container Images Certified by RedHat.
- [ ] https://github.com/kubearmor/kubearmor-relay-server/pull/35
- [ ] https://github.com/kubearmor/KubeArmor/pull/1348
- [x] Add CI workflow to test KubeArmor UBI image to be tested on bpflsm-crio env
```
