### ISSUE TITLE
Add support for Rabbitmq and Sidekick

### ISSUE THREAD

**Issue by Shreyas220** [kubearmor/KubeArmor#1215]
## Feature Request

To scale the relay server for more 100 nodes we need to create large Buffer which starts to consume alot of resources and we are now looking into optimizing them. 
Instead of doing this we can leverage already present solution like Message Queue to handle the scale  

#### Task 
- 1 Add support for Rabbitmq 
- 2 Create a custom Falco Sidekick to export events  

**Short Description**

#### Parameters to keep in mind
- Performance - make sure that Rabbitmq can scale to handle the increased load 
- Ack - Acknowledgement
- TTL - Time to live, a log shouldn't be persisted, after a certain interval the logs should be deleted 
- Priority Queue - Prioritize based on the type of event, Alerts should have a higher priority over msgs or logs 

# **Describe the solution you'd like**

## Architecture 

![image](https://user-images.githubusercontent.com/55346934/236383844-869f08c7-4244-4634-a8bc-b0cb4a568f22.png)

### Reasons to adopt SideKick 

1. Extensibility - we can use any desired solution to send logs for example disocrd rabbitmq or anything else the plugin is built for

2. Load balancing - sidekick will autoscale to handle increased load..

### Action Items 

- add logic to publish to rabbitmq 
- Add logic in Discovery engine to look for if its rabbitmq or relayser and connect to it, adding logic to consume 
- Add logic in Karmor engine to look for if its rabbitmq or relayser and connect to it, adding logic to consume 
- Change Sidekick code to consume logs from message queue and export it using the plugIn.

#### the code will look something like this 

we create a new client in logstruct 

```go
conn, err := amqp.Dial(rabbitmqurl)

amqpChannel, err := conn.Channel()

logcon := make(chan *pb.Log)
	defer close(conn)
ls.addLogStruct(uid, logcon, req.Filter)
	defer ls.removeLogStruct(uid)
	
```

#### Previous Design
![image](https://user-images.githubusercontent.com/55346934/236383453-b100b472-d7ff-410a-b2da-2b0894ef2c0d.png)

#### new Design 
![image](https://user-images.githubusercontent.com/55346934/236383480-50de4118-826b-4c66-b536-410bd21900a1.png)

### old 
![image](https://user-images.githubusercontent.com/55346934/236383313-38314ca2-0ccc-438c-8138-f26c12568f33.png)

### new
![image](https://user-images.githubusercontent.com/55346934/236383329-228615a2-5f21-482c-9bc8-e864d080ee76.png)
```[tasklist]
### Tasks
- [ ] add logic to publish to rabbitmq in Kubearmor
- [ ] To consume Logs - Add logic in Karmor  to look for if its rabbitmq or relayser and connect to it
- [ ] add feature to install Rabbitmq in Karmor client
- [ ] To Consume logs in Discovery Engine- Add logic in Discovery engine to look for if its rabbitmq or relayser and connect to it
- [ ] Create a custom Falco Sidekick to export events
```

**Comment by Parthiba-Hazra** [comment]
Hi @Shreyas220 ,
Is this issue already worked on?
If not then can I give it a try?

**Comment by Shreyas220** [comment]
> Hi @Shreyas220 , Is this issue already worked on? If not then can I give it a try?

Hey @Parthiba-Hazra, Please go on ahead
This is a big work item, please let me know which part would you like to work on 


if you need any clarification please reach out to me here or on kubearmor slack

**Comment by Parthiba-Hazra** [comment]
yeah, sure.
I will reach out to you once I clarify all the necessary things.

**Comment by Shreyas220** [comment]
> yeah, sure. I will reach out to you once I clarify all the necessary things.

wonderful 
please read the [code](https://github.com/kubearmor/KubeArmor/blob/46513d5b46e2c2ef4ebbe81a6c1767f7822bd59c/KubeArmor/feeder/feeder.go#L564) to understand how we are sending logs to relay server and how relay server connects to kubearmor [code](https://github.com/kubearmor/kubearmor-relay-server/blob/ed4549f614474e6d0b0d5851d768b0a9e4f47bcf/relay-server/server/relayServer.go#L639)

**Comment by Shreyas220** [comment]
Hey @Parthiba-Hazra any update on this issue ?

**Comment by Parthiba-Hazra** [comment]
> Hey @Parthiba-Hazra any update on this issue ?

Hey @Shreyas220 sorry for the delay..
I think I can start work on the first 3 tasks.. 
- add logic to publish to rabbitmq in Kubearmor
- To consume Logs - Add logic in Karmor to look for if its rabbitmq or relayser and connect to it
- add feature to install Rabbitmq in Karmor client

but before that I have some doubts to clear.. I will connect you on slack ..

**Comment by VedRatan** [comment]
@Parthiba-Hazra are you still working on this one? If yes, then please go ahead, if no then please do let us know.

**Comment by Shreyas220** [comment]
> @Parthiba-Hazra are you still working on this one? If yes, then please go ahead, if no then please do let us know.

@VedRatan we decided not to go with this approach.
