### ISSUE TITLE
 Remove use of cluster-admin role

### ISSUE THREAD

**Issue by achrefbensaad** [kubearmor/KubeArmor#1319]
## Feature Request

**Short Description**

Currently kubearmor is making use of the `cluster-admin` role. we would like to use a least privileged role instead.

**Describe the solution you'd like**

Kubearmor will be deployed using a least privileged role.

```[tasklist]
### Tasks
- [ ] Identify permissions needed by kubearmor to operate properly
- [ ] Update `deployments/` and other manifests with the new role and bindings
- [ ] Update kubearmor-client
```

**Comment by achrefbensaad** [comment]
Already solved in https://github.com/kubearmor/KubeArmor/pull/1253
