### ISSUE TITLE
RedHat Microshift support

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#1325]
## Feature Request

**Short Description**

Edge devices deployed out in the field pose very different operational, environmental, and business challenges from those of cloud computing. These motivate different engineering trade-offs for Kubernetes at the far edge than for cloud or near-edge scenarios. 

[MicroShift](https://microshift.io/) is an experimental flavor of OpenShift/Kubernetes optimized for the device edge. It targets the niche between minimal, standalone Linux edge devices and full-fledged OpenShift/Kubernetes edge clusters.

For reference, check the KubeArmor support on [Amazon Linux 2023](https://aws.amazon.com/linux/amazon-linux-2023/)

## Tasks

Install KubeArmor on Microshift and :

- [x] Check if policy enforcement, observability, audit rules, network segmentation is supported
- [x] Get output of `karmor probe`
- [x] Update [kubearmor support matrix](https://github.com/kubearmor/KubeArmor/blob/main/getting-started/support_matrix.md)
- [x] Provide and attach `karmor sysdump`

Also get Kernel information details by getting access to the host and using following command:
```
curl -s https://raw.githubusercontent.com/nyrahul/linux-kernel-configs/main/lk-config-get.sh | bash -s
```
This will create a folder with the distribution name.

**Comment by HariVamsiK** [comment]
Hey @nyrahul @Ankurk99 I can work on this. Can you assign it to me?
