### ISSUE TITLE
v0.11 release checklist

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#1338]
## Release Checklist

[Backlog Status](https://github.com/orgs/kubearmor/projects/17/views/1)

- [x] Manual Tests
    - [x] BottleRocket - BPF-LSM
    - [x] GKE COS (AppArmor)
    - [x] GKE COS (BPF-LSM)
    - [x] RHEL (certain BPF_LSM primitives are not available on RHEL)
    - [x] Amazon Linux 2
    - [x] minikube
    - [x] Quick check of performance vis-a-vis earlier version [^1]
- [x] MarketPlace Image updates
    - [x] [AWS/EKS Marketplace](https://aws.amazon.com/marketplace/pp/prodview-5npox4ixz64qk)
    - [x] [RedHat Catalog](https://catalog.redhat.com/software/container-stacks/detail/6368860f558779d5f81e157e)
- [x] [Release Blog](https://github.com/kubearmor/KubeArmor/wiki/v0.11-Release-Blog)
- [x] [Mark as stable release](https://github.com/kubearmor/KubeArmor/blob/main/STABLE-RELEASE)
- [x] Does it require a manual update to [Operator bundle](https://github.com/kubearmor/KubeArmor/tree/main/pkg/KubeArmorOperator/bundle)? (No change required)

> Note: Release checklist is needed since testing of certain platforms is not automated in CI env due to non-technical (primarily cost) concerns.

[^1]: Performance check: The easiest way is to deploy the current stable and the latest on the same k8s cluster and check the variation in performance.
