### ISSUE TITLE
v1.0.2 release checklist

### ISSUE THREAD

**Issue by ShubhamTatvamasi** [kubearmor/KubeArmor#1443]
## Release Checklist

[Backlog Status](https://github.com/orgs/kubearmor/projects/17/views/1)

- [x] Manual Tests
    - [ ] EKS - BottleRocket (Has issues running kubearmor, as mentioned [here](https://github.com/kubearmor/KubeArmor/issues/1443#issuecomment-1760860390) (https://github.com/kubearmor/KubeArmor/pull/1512)
    - [x] EKS - Amazon Linux 2
    - [x] GKE COS (AppArmor)
    - [x] GKE COS (BPF-LSM)
    - [x] RHEL (certain BPF_LSM primitives are not available on RHEL)
    - [x] minikube - VM Based 
    - [x] AKS Cluster - Ubuntu
    - [x] AKS Cluster - Azure Linux - No AppArmor packages
    - [x] VM support - test kubearmor packages without k8s on RHEL and Debian based systems
    - [ ] KubeArmor Performance [Benchmarking Data](https://github.com/kubearmor/KubeArmor/wiki/KubeArmor-Performance-Benchmarking-Data) for BPF-LSM
- [x] MarketPlace Image updates
    - [x] [AWS/EKS Marketplace](https://aws.amazon.com/marketplace/pp/prodview-5npox4ixz64qk)
    - [x] [RedHat Catalog](https://catalog.redhat.com/software/container-stacks/detail/6368860f558779d5f81e157e)
- [ ] [Release Blog](https://github.com/kubearmor/KubeArmor/wiki/v1.0-Release-Blog)
- [x] [Mark as stable release](https://github.com/kubearmor/KubeArmor/blob/main/STABLE-RELEASE)
- [x] Update to getting-started guide for helm
- [x] Does it require a manual update to [Operator bundle](https://github.com/kubearmor/KubeArmor/tree/main/pkg/KubeArmorOperator/bundle)? (No change required)
- [ ] Check helm charts has been released

> Note: Release checklist is needed since testing of certain platforms is not automated in CI env due to non-technical (primarily cost) concerns.

**Comment by nyrahul** [comment]
@PrimalPimmy , can you update the status on this issue?

**Comment by PrimalPimmy** [comment]
@nyrahul the bottlerocket version is not working for me, getting the following error in the kubectl logs:
```
2023-10-12 15:59:32.705566	INFO	Initialized KubeArmor Logger
2023-10-12 15:59:32.706557	INFO	Detected mounted BPF filesystem at /sys/fs/bpf
2023-10-12 15:59:32.707026	INFO	Initializing eBPF system monitor
2023-10-12 15:59:32.710507	WARN	Error closing stdin close |1: file already closed

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x18bb04c]

goroutine 1 [running]:
github.com/cilium/ebpf.(*Map).Update(0x1c7fd00?, {0x1c7fd00?, 0xc00005cd98?}, {0x1e4f280?, 0xc00051e0a0?}, 0x1c7b5c0?)
	/go/pkg/mod/github.com/cilium/ebpf@v0.11.0/map.go:700 +0x2c
github.com/cilium/ebpf.(*Map).Put(...)
	/go/pkg/mod/github.com/cilium/ebpf@v0.11.0/map.go:695
github.com/kubearmor/KubeArmor/KubeArmor/monitor.(*SystemMonitor).UpdateNsKeyMap(0xc000003b00, {0x1e8c090?, 0x18b8105?}, {0x0, 0x0}, {0x10?, 0x0?, 0x0?, 0x0?})
	/usr/src/KubeArmor/KubeArmor/monitor/systemMonitor.go:290 +0x548
github.com/kubearmor/KubeArmor/KubeArmor/monitor.(*SystemMonitor).UpdateHostVisibility(0xc000003b00)
	/usr/src/KubeArmor/KubeArmor/monitor/systemMonitor.go:355 +0x18c
github.com/kubearmor/KubeArmor/KubeArmor/monitor.(*SystemMonitor).initBPFMaps(0xc000003b00)
	/usr/src/KubeArmor/KubeArmor/monitor/systemMonitor.go:224 +0xff
github.com/kubearmor/KubeArmor/KubeArmor/monitor.(*SystemMonitor).InitBPF(0xc000003b00)
	/usr/src/KubeArmor/KubeArmor/monitor/systemMonitor.go:395 +0x297
github.com/kubearmor/KubeArmor/KubeArmor/core.(*KubeArmorDaemon).InitSystemMonitor(0xc00063a8c0)
	/usr/src/KubeArmor/KubeArmor/core/kubeArmor.go:231 +0x8e
github.com/kubearmor/KubeArmor/KubeArmor/core.KubeArmor()
	/usr/src/KubeArmor/KubeArmor/core/kubeArmor.go:435 +0x969
main.main()
	/usr/src/KubeArmor/KubeArmor/main.go:61 +0x1c8
	```

**Comment by Aryan-sharma11** [comment]
> @nyrahul the bottlerocket version is not working for me, getting the following error in the kubectl logs:
> 
> ```
> 2023-10-12 15:59:32.705566	INFO	Initialized KubeArmor Logger
> 2023-10-12 15:59:32.706557	INFO	Detected mounted BPF filesystem at /sys/fs/bpf
> 2023-10-12 15:59:32.707026	INFO	Initializing eBPF system monitor
> 2023-10-12 15:59:32.710507	WARN	Error closing stdin close |1: file already closed
> 
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x18bb04c]
> 
> goroutine 1 [running]:
> github.com/cilium/ebpf.(*Map).Update(0x1c7fd00?, {0x1c7fd00?, 0xc00005cd98?}, {0x1e4f280?, 0xc00051e0a0?}, 0x1c7b5c0?)
> 	/go/pkg/mod/github.com/cilium/ebpf@v0.11.0/map.go:700 +0x2c
> github.com/cilium/ebpf.(*Map).Put(...)
> 	/go/pkg/mod/github.com/cilium/ebpf@v0.11.0/map.go:695
> github.com/kubearmor/KubeArmor/KubeArmor/monitor.(*SystemMonitor).UpdateNsKeyMap(0xc000003b00, {0x1e8c090?, 0x18b8105?}, {0x0, 0x0}, {0x10?, 0x0?, 0x0?, 0x0?})
> 	/usr/src/KubeArmor/KubeArmor/monitor/systemMonitor.go:290 +0x548
> github.com/kubearmor/KubeArmor/KubeArmor/monitor.(*SystemMonitor).UpdateHostVisibility(0xc000003b00)
> 	/usr/src/KubeArmor/KubeArmor/monitor/systemMonitor.go:355 +0x18c
> github.com/kubearmor/KubeArmor/KubeArmor/monitor.(*SystemMonitor).initBPFMaps(0xc000003b00)
> 	/usr/src/KubeArmor/KubeArmor/monitor/systemMonitor.go:224 +0xff
> github.com/kubearmor/KubeArmor/KubeArmor/monitor.(*SystemMonitor).InitBPF(0xc000003b00)
> 	/usr/src/KubeArmor/KubeArmor/monitor/systemMonitor.go:395 +0x297
> github.com/kubearmor/KubeArmor/KubeArmor/core.(*KubeArmorDaemon).InitSystemMonitor(0xc00063a8c0)
> 	/usr/src/KubeArmor/KubeArmor/core/kubeArmor.go:231 +0x8e
> github.com/kubearmor/KubeArmor/KubeArmor/core.KubeArmor()
> 	/usr/src/KubeArmor/KubeArmor/core/kubeArmor.go:435 +0x969
> main.main()
> 	/usr/src/KubeArmor/KubeArmor/main.go:61 +0x1c8
> 	```
> ```
Hey, I deployed kubearmor on EKS bottlerocket the issue mentioned here was not reproducible for me.
![image](https://github.com/kubearmor/KubeArmor/assets/54109867/e19e4c47-8668-4c07-a445-19c5aa414202)
![image](https://github.com/kubearmor/KubeArmor/assets/54109867/9208fe73-a8b2-493f-88e8-aa6acc7159fc)
![image](https://github.com/kubearmor/KubeArmor/assets/54109867/c944cc9c-225c-4945-99bd-21a9667fe2d7)

**Comment by rksharma95** [comment]
updated images and published new release of KubeArmor on RedHat Ecosystem and AWS Marketplace.
https://github.com/redhat-openshift-ecosystem/certified-operators/pull/3026
https://aws.amazon.com/marketplace/pp/prodview-5npox4ixz64qk

**Comment by igorgolm** [comment]
@Aryan-sharma11 good day, I have the same issues on Bottlerocket and EKS as @PrimalPimmy has.  Kubearmor is installed with helm chart 
![image](https://github.com/kubearmor/KubeArmor/assets/61783021/49a236f1-50d2-4524-9c0f-54e76dc2c798)
it runs well on init setup, but when kubearmor pod restarts - it gives such issues

**Comment by daemon1024** [comment]
Bottlerocket issues fixed.

We will be creating the new release within this week :D Testing is in progress. You can track it at #1516
