### ISSUE TITLE
v1.1.0 release checklist

### ISSUE THREAD

**Issue by ShubhamTatvamasi** [kubearmor/KubeArmor#1516]
## Release Checklist

[Backlog Status](https://github.com/orgs/kubearmor/projects/17/views/1)

- [x] Manual Tests
    - [x] EKS - BottleRocket
    - [x] EKS - Amazon Linux 2
    - [x] GKE COS (AppArmor)
    - [x] GKE COS (BPF-LSM)
    - [x] RHEL (certain BPF_LSM primitives are not available on RHEL)
    - [x] minikube - VM Based 
    - [x] AKS Cluster - Ubuntu
    - [ ] AKS Cluster - Azure Linux - No AppArmor packages
    - [x] VM support - test kubearmor packages without k8s on RHEL and Debian based systems
    - [ ] KubeArmor Performance [Benchmarking Data](https://github.com/kubearmor/KubeArmor/wiki/KubeArmor-Performance-Benchmarking-Data) for BPF-LSM
- [ ] MarketPlace Image updates
    - [ ] [AWS/EKS Marketplace](https://aws.amazon.com/marketplace/pp/prodview-5npox4ixz64qk)
    - [ ] [RedHat Catalog](https://catalog.redhat.com/software/container-stacks/detail/6368860f558779d5f81e157e)
    - [ ] [MicroK8s Plugin](https://github.com/canonical/microk8s-community-addons/blob/main/addons/kubearmor/)
    - [ ] [Digital Ocean 1ClickApp](https://marketplace.digitalocean.com/apps/kubearmor)
- [ ] [Release Blog](https://github.com/kubearmor/KubeArmor/wiki/v1.0-Release-Blog)
- [x] [Mark as stable release](https://github.com/kubearmor/KubeArmor/blob/main/STABLE-RELEASE)
- [x] Update to getting-started guide for helm
- [ ] Does it require a manual update to [Operator bundle](https://github.com/kubearmor/KubeArmor/tree/main/pkg/KubeArmorOperator/bundle)? (No change required)
- [ ] Check helm charts has been released

> Note: Release checklist is needed since testing of certain platforms is not automated in CI env due to non-technical (primarily cost) concerns.
