### ISSUE TITLE
support for Alibaba Cloud VM/clusters

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#1650]
[Alibaba Cloud](https://www.alibabacloud.com/), also known as Aliyun, is a cloud computing company, a subsidiary of Alibaba Group. Alibaba Cloud provides cloud computing services to online businesses and Alibaba's own e-commerce ecosystem.

Users of KubeArmor have requested support for Alibaba Cloud deployments such as ACK (Alibaba Cloud k8s), Elastic Compute Services (Virtual Machines).

```[tasklist]
### Tasks
- [x] Alibaba Elastic Compute Services (Alibaba Cloud Linux 3.2104 LTS 64 bit)
- [x] Alibaba k8s clusters
- [x] Get detailed [linux-kernel-config](https://github.com/nyrahul/linux-kernel-configs)
- [x] Audit/Observability supported?
- [x] enforcement supported? What is the LSM used?
- [x] Paste the output of karmor probe
```

**Comment by nyrahul** [comment]
The latest image of Alibaba Cloud Linux 3 contains BPF-LSM enabled by default as part of the kernel config but not enabled by default as part of the boot parameter. Thus the user has to enable the bpf-lsm boot parameter for all the nodes for which they desire that the enforcement should work. [This](https://github.com/kubearmor/KubeArmor/blob/main/getting-started/FAQ.md#checking-and-enabling-support-for-bpf-lsm) (and [this for k8s](https://github.com/kubearmor/KubeArmor/blob/main/getting-started/FAQ.md#debug-kubearmor-installation-issue)) FAQ helps user with enabling bpf-lsm for VM and k8s env. Note that the nodes will be restarted once for the bpf-lsm boot parameter to come into effect.

The detailed linux-kernel-config for Alibaba Cloud Linux 3 can be found [here](https://github.com/nyrahul/linux-kernel-configs/tree/main/Alibaba%20Cloud%20Linux%203%20(Soaring%20Falcon)/5.10.134-16.1.al8.x86_64).
