### ISSUE TITLE
v1.3.1 release checklist

### ISSUE THREAD

**Issue by daemon1024** [kubearmor/KubeArmor#1675]
## Release Checklist

[Backlog Status](https://github.com/orgs/kubearmor/projects/17/views/1)

- [x] Manual Tests
    - [x] EKS - BottleRocket
    - [x] EKS - Gravitron (ARM64)
    - [x] EKS - Amazon Linux 2
    - [x] GKE COS (AppArmor)
    - [x] GKE COS (BPF-LSM)
    - [x] RHEL (certain BPF_LSM primitives are not available on RHEL)
    - [x] minikube - VM Based 
    - [x] AKS Cluster - Ubuntu
    - [x] AKS Cluster - Azure Linux - No AppArmor packages
    - [x] VM support - test kubearmor packages without k8s on RHEL and Debian based systems
    - [x] VM Support - Docker Compose
    - [x] KubeArmor Performance [Benchmarking Data](https://github.com/kubearmor/KubeArmor/wiki/KubeArmor-Performance-Benchmarking-Data) for BPF-LSM
    - [x] Seccomp implementation in all cluster envs mentioned above 
- [ ] MarketPlace Image updates
    - [ ] [AWS/EKS Marketplace](https://aws.amazon.com/marketplace/pp/prodview-5npox4ixz64qk)
    - [x] [RedHat Catalog](https://catalog.redhat.com/software/container-stacks/detail/6368860f558779d5f81e157e)
    - [ ] [MicroK8s Plugin](https://github.com/canonical/microk8s-community-addons/blob/main/addons/kubearmor/)
    - [ ] [Digital Ocean 1ClickApp](https://marketplace.digitalocean.com/apps/kubearmor)
- [ ] [Release Blog](https://github.com/kubearmor/KubeArmor/wiki/v1.0-Release-Blog)
- [x] [Mark as stable release](https://github.com/kubearmor/KubeArmor/blob/main/STABLE-RELEASE)
- [ ] Update to getting-started guide for helm
- [ ] Does it require a manual update to [Operator bundle](https://github.com/kubearmor/KubeArmor/tree/main/pkg/KubeArmorOperator/bundle)? (No change required)
- [x] Check helm charts has been released

> Note: Release checklist is needed since testing of certain platforms is not automated in CI env due to non-technical (primarily cost) concerns.

**Comment by daemon1024** [comment]
- [x] EKS - Barun
- [x] GKE - Barun
- [ ] RHEL and Marketplace - Ramakant
- [x] VM Support - Rudraksh
- [x] Minikube - Prashant
- [ ] Azure - Prateek

**Comment by DelusionalOptimist** [comment]
Release blog items:
- KubeArmor operator is the default way to install KA now
  - `karmor install` internally uses KubeArmor Operator's helm chart - https://github.com/kubearmor/kubearmor-client/pull/402
- Capabilities support with BPF LSM - https://github.com/kubearmor/KubeArmor/issues/1538
- Execname support in KA policies - https://github.com/kubearmor/KubeArmor/pull/1664
- Securing KubeArmor
  - KubeArmor secured using Seccomp - https://github.com/kubearmor/KubeArmor/pull/1661
  - Secure gRPC connection between KubeArmor and clients - https://github.com/kubearmor/KubeArmor/pull/1526
- Additional columns for policies - https://github.com/kubearmor/KubeArmor/pull/1683
- Support matrix
  - KubeArmor supports Alibaba Cloud - https://github.com/kubearmor/KubeArmor/blob/main/getting-started/support_matrix.md
- Performance improvements
  - Filter watched nodes and pods in KubeArmor - https://github.com/kubearmor/KubeArmor/pull/1676
