### ISSUE TITLE
version release and branching strategy/handling

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#590]
## Feature Request

**Short Description**

KubeArmor is now in active use in several POCs/deployments. It is expected that we have a clear branch and version release strategy enforced using CI practices.

**Describe the solution you'd like**

* `main` as our bleeding edge branch where things might be unstable.
* Release kubearmor every month or two with a new release version and release logs ... the versioning will be v0.2, v0.3 and so on ... If there are any backports, those will be handled as part of release-candidates version .. for e.g. v0.2-rc1, v0.2-rc2 and so on
* Every version (including release candidates) will have a tag created.
* Every version (not including release candidates) will have a branch name corresponding to the version name (for e.g., v0.2).
* KubeArmor dockerhub image will have following:
   * `kubearmor/kubearmor:latest` pointing to main branch image
   * `kubearmor/kubearmor:v0.2` ... version specific image ... release candidates will update this image itself for the corresponding version
   * `kubearmor/kubearmor:stable` ... a version will be upgraded to stable version only after enough due diligence (what this due diligence is would be considered in the future) .. for e.g., we might have v0.2, v0.3 as existing versions but stable might point to v0.2
* `karmor` cli tool and helm charts will ensure that the right accessory tooling (for e.g., kubearmor-relay-server) is made use of for the appropriate kubearmor version.
* Use community call to discuss backporting requirements

**Tasks**
- [x] GH Action to create docker image tag based on branch-name
- [x] CI tests to be done on the corresponding branch images
- [x] Map `stable` tag to one of the stable release based on a STABLE-RELEASE file.

**Checklist for new release/release-candidate**
- [x] Create branch (not applicable for release-candidate)
- [x] Create tag
- [x] Announcements (on slack)

** Side Tasks **
- [x] Remove dependency on `kubearmor-test-k3s.yaml`
- [x] Provide a way to show up that the release is getting create for a version release
