### ISSUE TITLE
support for ARM platform

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#614]
## Feature Request

**Short Description**

KubeArmor project has garnered interests from edge computing platforms (such as [LF Edge OpenHorizon](https://www.lfedge.org/projects/openhorizon/)). The primary requirement is to support several ARM platforms that are prevalent on the edge devices. KubeArmor uses kernel primitives which have been in use for several years and hence percolated across multiple platforms including ARM. However, there are primitives such as eBPF that have got into kernel recently and are in use by kubearmor and whose behaviour/handling might differ for ARM platform.

The aim of this issue is to:
1. Support kubearmor policy enforcement, visibility and alerts/telemetry on ARM platform.
2. Specifically Raspberry PI (RPI) platform would be used for tests purposes. Primary analysis suggests RPI supports AppArmor LSM and thus should be ok to work with. We will use the [latest RPI OS release](https://github.com/nyrahul/linux-kernel-configs/tree/main/Raspbian%20GNU_Linux%2010%20(buster)/5.10.17-v7l+).
3. KubeArmor could be used in systemd mode or in containerized mode.
4. Update release procedures for kubearmor to support ARM

**Describe the solution you'd like**

- [x] Prepare design/implementation plan to bridge the gaps.
- [x] Test KubeArmor on ARM platform. Analyze the gaps.
- [ ] Implementation and system tests
- [ ] Release procedures update

**Comment by Ankurk99** [comment]
Done as part of v0.7 release https://github.com/kubearmor/KubeArmor/wiki/v0.7-Release-Blog
