### ISSUE TITLE
supporting non-orchestrated containerized workloads

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#693]
## Feature Request

**Short Description**

KubeArmor is now getting deployed on non-orchestrated containerized workloads. Kubearmor has requirement to operate in this mode for [LFEdge OpenHorizon](https://www.lfedge.org/projects/openhorizon/).

Kubearmor currently creates security profiles by:
* listening to events from k8s
* In systemd mode, it operates directly on the processes running on the host.

The new mode to be supported is to:
* listen to events from docker or containerd directly and apply policies by specifying apparmor policy directly to the docker daemon.

**Is your feature request related to a problem? Please describe the use case.**

Containerized workloads are increasingly used for the edge scenarios. In most cases, these containers are not orchestrated but they need the same level of protection that is offered to orchestrated workloads by kubearmor.

**Describe the solution you'd like**

Docker/containerd allows one to specify the apparmor/selinux policy directly as a command line option. Utilize this feature for kubearmor to specify the policy. When the user applies the policy, the kubearmor will create the apparmor policy in the context for the given container and then [ask docker](https://docs.docker.com/engine/security/apparmor/) to apply the policy.

Note that currently we do not have a way to specify a container within the kubearmor security policy. However, with #675 we had identified on how this can be specified. We can leverage the same policy spec in this case.

**Tasks**
- [x] kubearmor (operating in systemd mode) to auto identify if there is a docker daemon running
- [x] wait for events on docker/containerd
- [x] get docker containers telemetry events and stream it through kubearmor grpc
- [x] create apparmor policy at runtime based on ksp (kubearmor security policy)
- [x] specify apparmor policy to the docker daemon and restart the workload
- [x] ability to refresh the apparmor policy on policy updates
- [x] changes to ksp to identify container for applying the policy
- [ ] karmor cli changes to specify the policies and to get the policies.

**Tests**
- [ ] System tests to be added as part of CI
- [ ] Execute multiple containers and apply policies in the context of a single container
- [x] Ensure that policies are reapplied on container restart
- [ ] If the container is already started and the policy is applied, the container has to be restarted.

**Docs**
- [ ] "Deploying Kubearmor to protect containerized workloads"
- [ ] Blog explaining IBM OpenHorizon POC with edge based containerized workloads
