### ISSUE TITLE
supporting Rancher RKE

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#771]
## Feature Request

Kubearmor has not be tested with [Rancher RKE](https://rancher.com/products/rke). The task involves setting up the sample cluster, verifying kubearmor operations on the cluster and making any fixes if necessary.

## Tasks
- [ ] setting up a sample cluster using Rancher RKE
- [ ] installing kubearmor on the sample cluster
- [ ] execute the automated tests on the sample cluster
- [ ] if kubearmor does not work, diagnose the issue
- [ ] discuss with the community and fix the issue
- [ ] update [kubearmor support matrix](https://github.com/kubearmor/KubeArmor/blob/main/getting-started/support_matrix.md)

**Comment by PrimalPimmy** [comment]
I'd like to work on this issue!

**Comment by PrimalPimmy** [comment]
So these 3 processes were not initializing properly and here are the logs (they have the same error) when testing on Rancher RKE:
<details>
  <summary>kubearmor-xg9bt</summary>
  
  ```
Name:         kubearmor-xg9bt
Namespace:    kube-system
Priority:     0
Node:         node1/10.0.2.15
Start Time:   Thu, 11 Aug 2022 16:52:59 +0530
Labels:       controller-revision-hash=85f9dcd674
              kubearmor-app=kubearmor
              pod-template-generation=1
Annotations:  container.apparmor.security.beta.kubernetes.io/kubearmor: unconfined
Status:       Pending
IP:           10.0.2.15
IPs:
  IP:           10.0.2.15
Controlled By:  DaemonSet/kubearmor
Init Containers:
  init:
    Container ID:   
    Image:          kubearmor/kubearmor-init:latest
    Image ID:       
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /lib/modules from lib-modules-path (ro)
      /media/root/etc/os-release from os-release-path (ro)
      /opt/kubearmor/BPF from bpf (rw)
      /sys/fs/bpf from sys-fs-bpf-path (rw)
      /sys/kernel/debug from sys-kernel-debug-path (rw)
      /sys/kernel/security from sys-kernel-security-path (rw)
      /usr/src from usr-src-path (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-kcj2c (ro)
Containers:
  kubearmor:
    Container ID:  
    Image:         kubearmor/kubearmor:stable
    Image ID:      
    Port:          32767/TCP
    Host Port:     32767/TCP
    Args:
      -gRPC=32767
      -logPath=/tmp/kubearmor.log
      -enableKubeArmorHostPolicy
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Liveness:       exec [/bin/bash -c if [ -z $(pgrep kubearmor) ]; then exit 1; fi;] delay=60s timeout=1s period=10s #success=1 #failure=3
    Environment:
      KUBEARMOR_NODENAME:   (v1:spec.nodeName)
    Mounts:
      /etc/apparmor.d from etc-apparmor-d-path (rw)
      /lib/modules from lib-modules-path (ro)
      /media/root/etc/os-release from os-release-path (ro)
      /opt/kubearmor/BPF from bpf (rw)
      /sys/fs/bpf from sys-fs-bpf-path (rw)
      /sys/kernel/debug from sys-kernel-debug-path (rw)
      /sys/kernel/security from sys-kernel-security-path (rw)
      /usr/src from usr-src-path (ro)
      /var/lib/docker from docker-storage-path (ro)
      /var/run/docker.sock from docker-sock-path (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-kcj2c (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  bpf:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  lib-modules-path:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:  Directory
  sys-fs-bpf-path:
    Type:          HostPath (bare host directory volume)
    Path:          /sys/fs/bpf
    HostPathType:  Directory
  sys-kernel-security-path:
    Type:          HostPath (bare host directory volume)
    Path:          /sys/kernel/security
    HostPathType:  Directory
  sys-kernel-debug-path:
    Type:          HostPath (bare host directory volume)
    Path:          /sys/kernel/debug
    HostPathType:  Directory
  os-release-path:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/os-release
    HostPathType:  File
  usr-src-path:
    Type:          HostPath (bare host directory volume)
    Path:          /usr/src
    HostPathType:  Directory
  etc-apparmor-d-path:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/apparmor.d
    HostPathType:  DirectoryOrCreate
  docker-sock-path:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/docker.sock
    HostPathType:  Socket
  docker-storage-path:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/docker
    HostPathType:  DirectoryOrCreate
  kube-api-access-kcj2c:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 op=Exists
                             node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/network-unavailable:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason       Age                    From     Message
  ----     ------       ----                   ----     -------
  Warning  FailedMount  15m (x58 over 3h16m)   kubelet  (combined from similar events): Unable to attach or mount volumes: unmounted volumes=[lib-modules-path], unattached volumes=[os-release-path usr-src-path lib-modules-path sys-fs-bpf-path bpf kube-api-access-kcj2c sys-kernel-debug-path docker-storage-path sys-kernel-security-path etc-apparmor-d-path docker-sock-path]: timed out waiting for the condition
  Warning  FailedMount  5m3s (x78 over 3h36m)  kubelet  MountVolume.SetUp failed for volume "lib-modules-path" : hostPath type check failed: /lib/modules is not a directory
  ```
</details>

<details>
<summary> kubearmor-hrc6f</summary>

  ```
Name:         kubearmor-hrc6f
Namespace:    kube-system
Priority:     0
Node:         node2/10.0.2.15
Start Time:   Thu, 11 Aug 2022 16:52:59 +0530
Labels:       controller-revision-hash=85f9dcd674
              kubearmor-app=kubearmor
              pod-template-generation=1
Annotations:  container.apparmor.security.beta.kubernetes.io/kubearmor: unconfined
Status:       Pending
IP:           10.0.2.15
IPs:
  IP:           10.0.2.15
Controlled By:  DaemonSet/kubearmor
Init Containers:
  init:
    Container ID:   
    Image:          kubearmor/kubearmor-init:latest
    Image ID:       
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /lib/modules from lib-modules-path (ro)
      /media/root/etc/os-release from os-release-path (ro)
      /opt/kubearmor/BPF from bpf (rw)
      /sys/fs/bpf from sys-fs-bpf-path (rw)
      /sys/kernel/debug from sys-kernel-debug-path (rw)
      /sys/kernel/security from sys-kernel-security-path (rw)
      /usr/src from usr-src-path (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-mjr6t (ro)
Containers:
  kubearmor:
    Container ID:  
    Image:         kubearmor/kubearmor:stable
    Image ID:      
    Port:          32767/TCP
    Host Port:     32767/TCP
    Args:
      -gRPC=32767
      -logPath=/tmp/kubearmor.log
      -enableKubeArmorHostPolicy
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Liveness:       exec [/bin/bash -c if [ -z $(pgrep kubearmor) ]; then exit 1; fi;] delay=60s timeout=1s period=10s #success=1 #failure=3
    Environment:
      KUBEARMOR_NODENAME:   (v1:spec.nodeName)
    Mounts:
      /etc/apparmor.d from etc-apparmor-d-path (rw)
      /lib/modules from lib-modules-path (ro)
      /media/root/etc/os-release from os-release-path (ro)
      /opt/kubearmor/BPF from bpf (rw)
      /sys/fs/bpf from sys-fs-bpf-path (rw)
      /sys/kernel/debug from sys-kernel-debug-path (rw)
      /sys/kernel/security from sys-kernel-security-path (rw)
      /usr/src from usr-src-path (ro)
      /var/lib/docker from docker-storage-path (ro)
      /var/run/docker.sock from docker-sock-path (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-mjr6t (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  bpf:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  lib-modules-path:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:  Directory
  sys-fs-bpf-path:
    Type:          HostPath (bare host directory volume)
    Path:          /sys/fs/bpf
    HostPathType:  Directory
  sys-kernel-security-path:
    Type:          HostPath (bare host directory volume)
    Path:          /sys/kernel/security
    HostPathType:  Directory
  sys-kernel-debug-path:
    Type:          HostPath (bare host directory volume)
    Path:          /sys/kernel/debug
    HostPathType:  Directory
  os-release-path:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/os-release
    HostPathType:  File
  usr-src-path:
    Type:          HostPath (bare host directory volume)
    Path:          /usr/src
    HostPathType:  Directory
  etc-apparmor-d-path:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/apparmor.d
    HostPathType:  DirectoryOrCreate
  docker-sock-path:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/docker.sock
    HostPathType:  Socket
  docker-storage-path:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/docker
    HostPathType:  DirectoryOrCreate
  kube-api-access-mjr6t:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 op=Exists
                             node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/network-unavailable:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason       Age                    From     Message
  ----     ------       ----                   ----     -------
  Warning  FailedMount  15m (x61 over 3h16m)   kubelet  (combined from similar events): Unable to attach or mount volumes: unmounted volumes=[lib-modules-path], unattached volumes=[sys-fs-bpf-path usr-src-path sys-kernel-debug-path sys-kernel-security-path os-release-path kube-api-access-mjr6t bpf etc-apparmor-d-path docker-sock-path docker-storage-path lib-modules-path]: timed out waiting for the condition
  Warning  FailedMount  5m3s (x75 over 3h36m)  kubelet  MountVolume.SetUp failed for volume "lib-modules-path" : hostPath type check failed: /lib/modules is not a directory
```

</details>

<details>

and <summary>wordpress-mysql blocked logs:</summary>

```
Name:           mysql-5df4cd65d5-gvwt8
Namespace:      wordpress-mysql
Priority:       0
Node:           node1/10.0.2.15
Start Time:     Thu, 11 Aug 2022 17:12:16 +0530
Labels:         app=mysql
                pod-template-hash=5df4cd65d5
Annotations:    container.apparmor.security.beta.kubernetes.io/mysql: localhost/kubearmor-wordpress-mysql-mysql-mysql
                kubearmor-policy: enabled
                kubearmor-visibility: process,file,network,capabilities
Status:         Pending
Reason:         AppArmor
Message:        Cannot enforce AppArmor: profile "kubearmor-wordpress-mysql-mysql-mysql" is not loaded
IP:
IPs:            <none>
Controlled By:  ReplicaSet/mysql-5df4cd65d5
Containers:
  mysql:
    Container ID:
    Image:          mysql:5.6
    Image ID:
    Port:           3306/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       Blocked
    Ready:          False
    Restart Count:  0
    Environment:
      MYSQL_ROOT_PASSWORD:  root-password
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-9kzjx (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-api-access-9kzjx:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age                     From     Message
  ----     ------       ----                    ----     -------
  Warning  FailedMount  5m13s (x77 over 3h26m)  kubelet  MountVolume.SetUp failed for volume "kube-api-access-9kzjx" : object "wordpress-mysql"/"kube-root-ca.crt" not registered
 
 
Name:           wordpress-c4bf5b44b-44mp8
Namespace:      wordpress-mysql
Priority:       0
Node:           node2/10.0.2.15
Start Time:     Thu, 11 Aug 2022 17:12:16 +0530
Labels:         app=wordpress
                pod-template-hash=c4bf5b44b
Annotations:    container.apparmor.security.beta.kubernetes.io/wordpress: localhost/kubearmor-wordpress-mysql-wordpress-wordpress
                kubearmor-policy: enabled
                kubearmor-visibility: process,file,network,capabilities
Status:         Pending
Reason:         AppArmor
Message:        Cannot enforce AppArmor: profile "kubearmor-wordpress-mysql-wordpress-wordpress" is not loaded
IP:
IPs:            <none>
Controlled By:  ReplicaSet/wordpress-c4bf5b44b
Containers:
  wordpress:
    Container ID:
    Image:          wordpress:4.8-apache
    Image ID:
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       Blocked
    Ready:          False
    Restart Count:  0
    Environment:
      WORDPRESS_DB_HOST:      mysql
      WORDPRESS_DB_PASSWORD:  root-password
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-5f6zv (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-api-access-5f6zv:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age                     From     Message
  ----     ------       ----                    ----     -------
  Warning  FailedMount  5m12s (x77 over 3h26m)  kubelet  MountVolume.SetUp failed for volume "kube-api-access-5f6zv" : object "wordpress-mysql"/"kube-root-ca.crt" not registered
```
</details>

**Comment by achrefbensaad** [comment]
RKE is now supported in kubearmor v0.6.
