### ISSUE TITLE
automating test scenarios in CI

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#801]
## Scenarios that needs to be added to [automated test framework](https://github.com/kubearmor/KubeArmor/tree/main/tests)

- [x] syscalls audit #737 (effort medium)
- [x] TCP connect, accept handling #779 (effort low)
- [x] bpflsm #741 (effort high)
- [x] [namespace based posture](https://github.com/kubearmor/KubeArmor/wiki/KubeArmor-version-release-v0.3#default-security-posture-daemon1024) (effort low)

---
If you are in interested in contributing, you should do the following:
1. pick up one of the unhandled point from the list
2. create a new issue for the same
3. add specific test cases that can be automated. Ask for a review for the testcases on the slack. We will assign someone to review. While the review is in progress you can start implementing test cases that are already identified (that is move onto the next step).
4. [add test suite](https://github.com/kubearmor/KubeArmor/tree/main/tests#how-to-add-a-new-testsuite) to the ginkgo framework .. for ref [check this](https://github.com/kubearmor/KubeArmor/blob/main/tests/smoke/smoke_test.go).

**Comment by aishwarya25252** [comment]
Can I take up this issue ? This will also help me learn more about ginkgo and kubearmor code base . Thanks

**Comment by nyrahul** [comment]
Hey @aishwarya25252 , I have added one more scenario to the issue .. Can you please check and figure if we could automate it?

**Comment by sarthaksarthak9** [comment]
@nyrahul  I think all the issues are done here
