### ISSUE TITLE
AWS FTR assesment tracker

### ISSUE THREAD

**Issue by rksharma95** [kubearmor/KubeArmor#891]
## Feature Request

**Short Description**

We are targeting the `KubeArmor` to meet all the specified requirements under [AWS Foundational Technical Review](https://apn-checklists.s3.amazonaws.com/foundational/customer-deployed/customer-deployed/C0hfGvKGP.html). This issue tracks the progress on the same. Most of the requirements are AWS platform specific. 

The spreadsheet document [here](https://docs.google.com/spreadsheets/d/17lSAHA8KhEtxsI7LYWakmdGVSszKD5gqY6wh80RkA5I/edit?usp=sharing) can be used for remark/discussion, feel free to add your remark there. The draft document [here](https://docs.google.com/document/d/1vcoILEaWTKibrbgXpW20470WbJxOrsHny8geOv6dGVE/edit?usp=sharing) is being used to track WIP.
**Describe the solution you'd like**
### Action Items
- [x] Respond to all the requirements with required action item. 
### Architecture Diagram
-  [x] Illustrate all AWS services running, demonstrate VPC and subnet requirements
### Documentation
- #### Introduction
-  [x] Use cases of the Kubearmor 
-  [x] List of resources deployed and expected amount of time to complete. ref: #875  
-  [x] Specify the supported regions
-  [x] Guidance fot testing/troubleshooting
- #### Requirements
-  [x] Technical prerequisites and requirements i.e. EKS Cluster, IAM Permissions etc.
-  [x] Specify if the specilized skills and knowlege needed
-  [x] Environment configuration that is needed, i.e. AWS account, OS, licensing etc.
- #### Security
-  [x] Specify that deployment doesn't require any root privileges
-  [x] Specify that deployment follows policy of least privilege 
-  [x] Describe purpose of each IAM role and policy to be created by the user
- #### Cost
-  [x] List of optional/mandatory billable service
-  [x] Licensing cost
- #### Sizing
-  [x] Either provide a script to provision required resource or provide guidance for type and size selection for the resource.
   Ref: #923 
- #### Health Check
-  [x] how to monitor the heath of the Kubearmor i.e. using karmor probe command
- #### Backup and Recovery
-  [x] data and configuration to be backed up i.e. backup applied kubearmor policies.
- #### Routine Maintenance
-  [x] rotating system credentials and cryptographic keys i.e. karmor rotate-tls
-  [x] guidance for software patches and upgrades i.e. karmor selfupdate
-  [x] guidance for managing licence and AWS service limits
- #### Emergency Maintenance
-  [x] instructions on handling fault conditions and how to recover the software.
- #### Support
-  [x] guidance on how to receive support, details on different technical support tiers and SLAs.

**Describe alternatives you've considered**

A separate section titled "KubeArmor on EKS" that answers all the requirements specified in the AWS FTR can be added to the Documentation.

**Comment by rksharma95** [comment]
I've added some remarks to the sheet. There are still some points that need to be discuss i marked those as `help wanted`.
