### ISSUE TITLE
supporting OpenTelemetry

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#894]
[OpenTelemetry](https://opentelemetry.io/) is a CNCF project that defines a telemetry protocol and data formats, it covers distributed tracing, metrics and logs. The project provides an SDK as well as a collector component that can run on Kubernetes. Typically, an application exposes OpenTelemetry data through direct instrumentation that is most often implemented in-app using OpenTelemetry SDK. An OpenTelemetry collector is used to gather data from various applications in a cluster, and send it to one or more backends. [Jaeger](https://jaegertracing.io/) (another CNCF project) is one of the backends that can be used for storage and presentation of trace data.

### Possible Design
Best to support an OpenTelemetry adapter to KubeArmor that receives KubeArmor logs/alerts/telemetry from the kubearmor-relay-service and converts it into open telemetry format.

### Tasks
- [ ] Create OpenTelemetry adapter for kubearmor
- [ ] Setup/Usage guide for using OpenTelemetry Adapter
- [ ] Demo integrations with any backend supporting OpenTelemetry

**Comment by sheharyaar** [comment]
Does this need to be added in kubearmor-relay-server ?

**Comment by nyrahul** [comment]
> Does this need to be added in kubearmor-relay-server ?

Yep, that seems to be the most logical way. Relay acts as a single point of contact where telemetry from across all nodes is available. Now we can another adapter which connects to kubearmor-relay-server and then emits OT output. This would not require any changes to the existing components. This would result in a new repo.

**Comment by amit-62** [comment]
Hey @nyrahul 
I'm interested in this project for LFX mentorship. How should I get started?

**Comment by Chinwendu20** [comment]
I am interested in working on this issue as an lfx mentee

**Comment by dipankardas011** [comment]
I am also interested

**Comment by nyrahul** [comment]
Folks, thank you for your interest. However, the mentors of this LFX project will take a call based on proposals submitted to [the LFX mentorship call](https://mentorship.lfx.linuxfoundation.org/project/a0696db8-509e-44ff-ae61-82a3442853c1) and subsequent evaluation based on artifacts submitted therein. Interests submitted on this GH issue **would not** be taken into account. So if you are interested please ensure that you submit your interest on the LFX mentorship project.

**Comment by mahesh-hegde** [comment]
Hi Rahul (@nyrahul) pardon me for continuing this thread, but I see only "Cover letter" and "Resume" among the artifacts to be uploaded in LFX dashboard. Am I missing something? (Is there a sample project we should complete?).

Also should the cover letter include a proposal?

**Comment by nyrahul** [comment]
> Hi Rahul (@nyrahul) pardon me for continuing this thread, but I see only "Cover letter" and "Resume" among the artifacts to be uploaded in LFX dashboard. Am I missing something? (Is there a sample project we should complete?).
> 
> Also should the cover letter include a proposal?

Yep, only the resume and cover letter has to be uploaded. The cover letter could briefly explain your intent and basic idea as to how you would like to shape this project. 

All good questions. Thank you for your interest.

**Comment by Chinwendu20** [comment]
Please assign this issue to me. This involves creating a new repo. How do I go about doing that under Kubearmor
